# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/max/Documents/cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/max/Documents/cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/max/Documents/cpp/CMakeFiles /Users/max/Documents/cpp/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/max/Documents/cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named obj

# Build rule for target.
obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 obj
.PHONY : obj

# fast build rule for target.
obj/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/build
.PHONY : obj/fast

#=============================================================================
# Target rules for targets named compressed

# Build rule for target.
compressed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compressed
.PHONY : compressed

# fast build rule for target.
compressed/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressed.dir/build.make CMakeFiles/compressed.dir/build
.PHONY : compressed/fast

#=============================================================================
# Target rules for targets named sparse

# Build rule for target.
sparse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sparse
.PHONY : sparse

# fast build rule for target.
sparse/fast:
	$(MAKE) $(MAKESILENT) -f sparse/CMakeFiles/sparse.dir/build.make sparse/CMakeFiles/sparse.dir/build
.PHONY : sparse/fast

# target to build an object file
compressed.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressed.dir/build.make CMakeFiles/compressed.dir/compressed.o
.PHONY : compressed.o

# target to preprocess a source file
compressed.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressed.dir/build.make CMakeFiles/compressed.dir/compressed.i
.PHONY : compressed.i

# target to generate assembly for a file
compressed.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compressed.dir/build.make CMakeFiles/compressed.dir/compressed.s
.PHONY : compressed.s

# target to build an object file
obj.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/obj.o
.PHONY : obj.o

# target to preprocess a source file
obj.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/obj.i
.PHONY : obj.i

# target to generate assembly for a file
obj.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/obj.dir/build.make CMakeFiles/obj.dir/obj.s
.PHONY : obj.s

# target to build an object file
parser.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.o
.PHONY : parser.o

# target to preprocess a source file
parser.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.i
.PHONY : parser.i

# target to generate assembly for a file
parser.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/parser.s
.PHONY : parser.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compressed"
	@echo "... obj"
	@echo "... parser"
	@echo "... sparse"
	@echo "... compressed.o"
	@echo "... compressed.i"
	@echo "... compressed.s"
	@echo "... obj.o"
	@echo "... obj.i"
	@echo "... obj.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

